### ISSUE TITLE
Investigate copying over /vx/config information when flashing an image

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vx-iso#25]
When we are overwriting a harddrive that already have VotingWorks software we should optionally have the ability in the program to copy the machine configuration info in /vx/config and preserve it after flashing a new image. This should be optional, and should not explode if you try to do it when VotingWorks software is not already configured on the machine. Work with @adghayes on what details should be copied over (i.e. everything in /vx/config? just some things?)

**Comment by umbernhard** [comment]
Thinking about this task: Do we want to only copy `/vx/config` or do we want to preserve the whole `/var` partition? That would preserve past election data if it hadn't been backed up.

I could also see this leading to a "Factory Reset" option in vx-iso that totally wipes a disk before flashing. @carolinemodic @benadida thoughts?

**Comment by carolinemodic** [comment]
I think we probably just want config for now but curious what @benadida thinks

**Comment by benadida** [comment]
> Thinking about this task: Do we want to only copy `/vx/config` or do we want to preserve the whole `/var` partition? That would preserve past election data if it hadn't been backed up.
> 
> I could also see this leading to a "Factory Reset" option in vx-iso that totally wipes a disk before flashing. @carolinemodic @benadida thoughts?

Interesting question! We could try keeping all of /var, though I'm a little worried about backwards compat requirements from then on. So maybe just config and logs?

**Comment by umbernhard** [comment]
more quirks: just copying `/vx/config` isn't enough. Other data, like the machine's hostname file, need to come too if we want to preserve that consistency. This raises and interesting question: hostname is kept under `/etc/`, which will be locked with dm-verity on production machines. That means we cannot change that file without recomputing the root hashes. We could make that part of our update process. @benadida @carolinemodic thoughts?

**Comment by umbernhard** [comment]
alternatively we could symlink `/etc/hostname -> /var/vx/config/hostname` or something

**Comment by benadida** [comment]
> more quirks: just copying `/vx/config` isn't enough. Other data, like the machine's hostname file, need to come too if we want to preserve that consistency. This raises and interesting question: hostname is kept under `/etc/`, which will be locked with dm-verity on production machines. That means we cannot change that file without recomputing the root hashes. We could make that part of our update process. @benadida @carolinemodic thoughts?

Changing the root hashes is not an option, right, since that would require one-off signing of each machine based on its hostname? I think we have to either set the hostname some other way, or just not change the hostname.

**Comment by benadida** [comment]
> Okay, so to clarify: the user should be prompted whether they want the config copied, and then the directory should be copied, ignoring other inconsistencies that may create (like hostname being out of sync with machine ID)?

Yes, exactly. I think we have to solve that separately anyways, either by putting hostname in `/vx/config`, or something else. As a separate ticket.
