### ISSUE TITLE
Build the ability to create an image from real hardware to vx-iso

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vx-iso#26]
There are a few different options for this as discussed in the doc: https://docs.google.com/document/d/1aYYNsknSWnqHvR2NLte2jAz79veIt4kuISrrcLZoCxM/edit# 

From a seperate conversation with @umbernhard it seems like a seperate bash script packaged in the same ISO file will be the simplest way to do this but I defer to @umbernhard on the simplest implementation approach. Ideally this option should be hidden entirely, or sufficiently hard to get to that a non-technical user using a preconfigured install stick won't get confused by it.

**Comment by umbernhard** [comment]
@carolinemodic how should I name image files? I could go with something generic, or I could prompt the user for a name, or maybe do something fancier like read /vx/config or something. Thoughts?
