### ISSUE TITLE
Define software in the field upgrade process

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vx-iso#28]
We will need to define the step by step flows of how this should work: 
- For each application/hardware we have in case there are differences: Flexpads, Thinkpads, Surface Gos
- For both the transition in m14 from pre-ESI machines to post-ESI machines
- For the eventual stable state of post-ESI machines to post-ESI machines

If there is additional work necessary to make sure that final flow in particular is as pain free as possible (should not require turning secure boot off, etc.) we should make tickets for that work as well.

**Comment by mattroe** [comment]
Defined!
