### ISSUE TITLE
Integrity check images before decompressing

### ISSUE THREAD

**Issue by umbernhard** [votingworks/vx-iso#46]
In the event that an image is corrupted after it is created but before it is to be flashed, we want to detect this before we try to put bits on disk. A hash of the compressed image should be created and shipped with the image, which should be checked by the flash script before decompressing and flashing. Note that the hash of the full image is still useful as a check that the flashing operation was successful.

**Comment by arsalansufi** [comment]
Closing this out as likely outdated
