### ISSUE TITLE
old drives are listed as possible image sources

### ISSUE THREAD

**Issue by benadida** [votingworks/vx-iso#53]
My arch vx-iso is listing disks that are not plugged in, `sda` and `sdb`, as possible image sources.

![image](https://user-images.githubusercontent.com/18057/179776927-90e06a9c-fe99-40aa-86cf-34fca554dddd.png)

Simplest solution might be to ask for partitions specifically, cause images might be on a diff partition of the current USB, too. And we could probably safely exclude all `nvme0n1` partitions.

**Comment by umbernhard** [comment]
Are we sure we don't have any devices that don't have an NVMe drive?

Also curious if you've repro'd with cold boot.

**Comment by arsalansufi** [comment]
Closing this out as likely outdated
