### ISSUE TITLE
Update Readme to reflect current installation process

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vx-iso#71]
The readme in this repo still has the instructions on how to create a vx-iso stick using Ventoy. We should update the instructions to be accurate to the latest process that is described in: https://docs.google.com/document/d/1anj1dhciof8xc0vLFqKaPkE2texWUx1rFdpCFcZmW5w/edit#heading=h.ixmei1a9bxjj

We could also link to a google doc with the instructions if that seems to be an easier way to maintain this.

**Comment by arsalansufi** [comment]
Closing this out as outdated
