### ISSUE TITLE
Fix partition you get Data from in vx-iso

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vx-iso#72]
Currently when scraping an image vx-iso is hardcoded to mount the third partition on a USB which doesn't actually make that much sense with how we are using vx-iso without Ventoy now. 

A bit seperate but I also found it hard to figure out which device was which when scraping an image. The prompt to chose which device to put the data in does not include the sizes of the devices, even though the previous prompt does, so you have to memorize which size usb is which device (sda vs sdb) when we could just give that info on both prompts. Would be even more useful if we could give the name of the usb device or something in case both usbs are the same size too.

**Comment by arsalansufi** [comment]
Closing this out as likely outdated
